import { test, expect } from '@playwright/test';

test('judge journey: dashboard → validation → assessment → saved result → follow-up → history → delete', async ({ page }) => {
  const errors: string[] = []; page.on('pageerror', error => errors.push(error.message));
  await page.goto('/');
  await expect(page.getByRole('heading', { name: 'Every student deserves to be seen.' })).toBeVisible();
  await expect(page.locator('.assessment-row')).toHaveCount(3);
  await page.locator('.hero').getByRole('link', { name: 'Check a concern' }).click();
  await page.getByRole('button', { name: 'Continue', exact: true }).click();
  await expect(page.getByText('Enter a nickname or anonymous identifier.')).toBeVisible();
  await page.getByRole('button', { name: 'Fill fictional example' }).click();
  await page.getByLabel('Student nickname / identifier').fill('Demo Journey');
  await page.getByRole('button', { name: 'Continue', exact: true }).click();
  await expect(page.getByLabel('Missing homework', { exact: true })).toBeChecked();
  await page.getByRole('button', { name: 'Continue', exact: true }).click();
  await page.getByRole('button', { name: 'Prepare & save guidance' }).click();
  await expect(page.getByText('Please review the safety question before continuing.')).toBeVisible();
  await page.getByLabel('I have reviewed the safety question.').check();
  // A controlled delay makes the genuine pending state observable without slowing the product.
  await page.route('**/api/assessments', async route => { if (route.request().method() === 'POST') await new Promise(resolve => setTimeout(resolve, 500)); await route.continue(); });
  await page.getByRole('button', { name: 'Prepare & save guidance' }).click();
  await expect(page.getByRole('status').filter({ hasText: 'Reviewing the observations' })).toBeVisible();
  await expect(page.getByRole('heading', { name: 'A way forward for Demo Journey.' })).toBeVisible();
  await expect(page.getByText('Saved to history')).toBeVisible();
  await expect(page.getByRole('heading', { name: 'A gentle way to begin' })).toBeVisible();
  await page.getByLabel('Follow-up date').fill('2028-04-20');
  await page.getByRole('button', { name: 'Save schedule' }).click();
  await expect(page.getByRole('status')).toContainText('Follow-up updated.');
  await page.getByRole('button', { name: 'Mark follow-up complete' }).click();
  await expect(page.getByRole('button', { name: 'Reopen follow-up' })).toBeVisible();
  await page.reload();
  await expect(page.getByRole('button', { name: 'Reopen follow-up' })).toBeVisible();
  await expect(page.getByLabel('Follow-up date')).toHaveValue('2028-04-20');
  await page.locator('.back-link').click();
  await page.getByLabel('Search student identifiers').fill('Demo Journey');
  await expect(page.locator('.history-row')).toHaveCount(1);
  await expect(page.locator('.history-row')).toContainText('Follow-up complete');
  await page.locator('.history-row').click();
  await page.getByRole('button', { name: 'Delete assessment', exact: true }).click();
  await page.getByRole('button', { name: 'Delete permanently' }).click();
  await expect(page.getByRole('heading', { name: 'Your record of care.' })).toBeVisible();
  await expect(page.locator('.history-row')).toHaveCount(3);
  expect(errors).toEqual([]);
});

test('safety bypass, resources, keyboard and responsive layout', async ({ page }) => {
  await page.goto('/');
  await expect(page.getByRole('heading', { name: 'Every student deserves to be seen.' })).toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  await page.locator('.assessment-row').filter({ hasText: 'Student C' }).click();
  await expect(page.getByRole('heading', { name: 'Immediate safety concern' })).toBeVisible();
  await expect(page.getByText('No local contacts are configured.', { exact: false })).toBeVisible();
  await expect(page.getByRole('heading', { name: 'A gentle way to begin' })).toHaveCount(0);
  await page.goto('/#/resources');
  await expect(page.getByRole('heading', { name: 'A little guidance. A lot of care.' })).toBeVisible();
  await page.getByLabel('Search resources').fill('bullying');
  await expect(page.locator('.resource-card')).toHaveCount(1);
  await page.getByText('Read practical guidance').click();
  await expect(page.getByText('Immediate threats or danger require the safeguarding route now.')).toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  await page.goto('/#/new');
  await page.getByRole('button', { name: 'Fill fictional example' }).click();
  await page.getByRole('button', { name: 'Continue', exact: true }).click();
  await page.getByLabel('What have you noticed?').fill('The student said they want to die.');
  await expect(page.getByRole('heading', { name: 'Immediate safety concern' })).toBeVisible();
  await page.getByRole('button', { name: 'Continue', exact: true }).click();
  await page.getByLabel('Self-harm or suicidal thoughts', { exact: true }).check();
  await page.getByLabel('I have reviewed these safety concerns').check();
  await page.getByRole('button', { name: 'Save safety concern' }).click();
  await expect(page.getByText('Safety pathway · Standard safeguarding guidance.', { exact: false })).toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
});

test('network failure offers recovery and assessment failure preserves notes', async ({ page }) => {
  await page.route('**/api/config', route => route.abort());
  await page.goto('/');
  await expect(page.getByRole('alert')).toContainText('couldn’t reach the server');
  await page.unroute('**/api/config');
  await page.getByRole('button', { name: 'Try again' }).click();
  await expect(page.getByRole('heading', { name: 'Every student deserves to be seen.' })).toBeVisible();
  await page.goto('/#/new');
  await page.getByRole('button', { name: 'Fill fictional example' }).click();
  await page.getByRole('button', { name: 'Continue', exact: true }).click();
  await page.getByRole('button', { name: 'Continue', exact: true }).click();
  await page.getByLabel('I have reviewed the safety question.').check();
  await page.route('**/api/assessments', route => route.request().method() === 'POST' ? route.fulfill({ status: 500, contentType: 'application/json', body: JSON.stringify({ error: 'We could not save. Try again.' }) }) : route.continue());
  await page.getByRole('button', { name: 'Prepare & save guidance' }).click();
  await expect(page.getByRole('alert')).toContainText('We could not save');
  await expect(page.locator('.review-box')).toContainText('missed two assignments');
});
