export type Resource = { id: string; title: string; category: string; minutes: number; intro: string; steps: string[]; takeaway: string; source: string; sourceTitle: string };
export const resources: Resource[] = [
  { id: 'notice', title: 'Look for changes, not labels', category: 'Noticing patterns', minutes: 3, intro: 'A change in participation can have many explanations. Start with what is different for this student, not a label for their behavior.', steps: ['Record what you saw or heard, when it happened, and how it differs from the student’s usual participation.', 'Consider whether routines, workload, or peer interactions have changed. Avoid guessing at a diagnosis or family situation.', 'A pattern is a reason to offer support, not proof of a condition. A single serious safety concern still needs prompt action.'], takeaway: '“Has been quiet in three discussions” is more useful than “doesn’t care.”', source: 'https://www.unicef.org/coronavirus/8-teacher-tips-student-mental-health', sourceTitle: 'UNICEF: supporting students’ mental health' },
  { id: 'conversation', title: 'A small conversation can help', category: 'Conversation guide', minutes: 4, intro: 'Create space for the student’s perspective without pressure to disclose personal details.', steps: ['Find a private, appropriate setting in line with school policy. Start with a neutral observation.', 'Ask one open question, allow time, and listen. Offer the option to speak with another trusted school adult.', 'Explain limits to confidentiality: if safety is involved, you will need to share with appropriate support staff. Agree one manageable next step.'], takeaway: '“I’ve noticed a change. Is there something at school we can help with?”', source: 'https://www.unicef.org/coronavirus/8-teacher-tips-student-mental-health', sourceTitle: 'UNICEF: guidance for teachers' },
  { id: 'worry', title: 'Make school feel more manageable', category: 'Everyday support', minutes: 3, intro: 'Predictable, flexible classroom support can help a student who appears worried without requiring a diagnosis.', steps: ['Offer clear instructions and break larger tasks into smaller steps.', 'Give a low-pressure way to participate and explain changes to routines in advance.', 'Ask what support would help. If the pattern continues, consult the school’s wellbeing staff.'], takeaway: 'Start with one classroom adjustment and review whether it helps.', source: 'https://www.unicef.org/coronavirus/8-teacher-tips-student-mental-health', sourceTitle: 'UNICEF: classroom wellbeing support' },
  { id: 'bullying', title: 'Respond to bullying concerns', category: 'Peer relationships', minutes: 4, intro: 'Take a student’s concern seriously and use the school’s reporting and support routes.', steps: ['Listen calmly and record factual information through the approved school process.', 'Follow the school’s bullying and safeguarding policies; avoid forcing a confrontation or mediation.', 'Check what will help the student feel safe at school, involve designated staff, and arrange a follow-up.'], takeaway: 'Immediate threats or danger require the safeguarding route now.', source: 'https://www.unicef.org/parenting/child-care/bullying', sourceTitle: 'UNICEF: responding to bullying' },
  { id: 'grief', title: 'Support a student through change', category: 'Life events', minutes: 3, intro: 'If a loss or major change is already known, offer flexibility without assuming how a student should feel.', steps: ['Acknowledge the situation briefly and let the student choose whether to talk.', 'Offer predictable routines and reasonable flexibility around schoolwork with appropriate staff.', 'Check in gently over time and involve school support when needed. Do not seek unnecessary details about the event.'], takeaway: 'There is no single way a student should respond to a loss.', source: 'https://www.unicef.org/eca/stories/how-talk-your-children-about-death-loved-one', sourceTitle: 'UNICEF: talking about loss' },
  { id: 'safeguarding', title: 'Know when to bring in support', category: 'Safeguarding basics', minutes: 5, intro: 'A tool or follow-up reminder does not replace your school’s safeguarding process. Know the designated contacts before you need them.', steps: ['For potential abuse, self-harm, threats, or immediate danger, follow school emergency and safeguarding procedures promptly.', 'Listen without investigating or leading questions. Do not promise secrecy.', 'Share factual concerns with the designated safeguarding professional; use the school’s escalation route if they are unavailable.'], takeaway: 'Use local school policy. These general principles do not replace local procedures or training.', source: 'https://learning.nspcc.org.uk/child-abuse-and-neglect/recognising-and-responding-to-abuse', sourceTitle: 'NSPCC Learning: recognising and responding to abuse (UK guidance)' },
];

