import { AlertTriangle, ArrowRight, BookOpen, Check, ChevronRight, Clock3, ShieldCheck, Sprout, type LucideIcon } from 'lucide-react';
import type { Assessment, SafetyConfig } from '../shared/schema';
import { localDate } from '../shared/schema';

export const go = (route: string) => { location.hash = `#${route}`; };
export function IconBox({ icon: Icon, tone = '' }: { icon: LucideIcon; tone?: string }) { return <span className={`icon-box ${tone}`}><Icon size={21} aria-hidden="true" /></span>; }
export function Brand() { return <div className="brand"><span className="brand-icon"><Sprout size={29} /></span><span>Teacher Awareness<span className="brand-sub">ASSISTANT</span></span></div>; }
export function Badge({ level, safety }: { level: Assessment['guidance']['concernLevel']; safety?: boolean }) { return <span className={`badge ${level}`}><span className="badge-dot" />{safety ? 'Safety concern' : `${level[0].toUpperCase()}${level.slice(1)} concern`}</span>; }
export function DateText({ value }: { value: string }) { return <>{new Date(value.length === 10 ? `${value}T12:00:00` : value).toLocaleDateString(undefined, { day: 'numeric', month: 'short', year: 'numeric' })}</>; }
export function PageHeading({ eyebrow, title, children, action }: { eyebrow: string; title: string; children?: React.ReactNode; action?: React.ReactNode }) { return <header className="page-heading"><div><span className="eyebrow">{eyebrow}</span><h1 tabIndex={-1}>{title}</h1>{children && <p>{children}</p>}</div>{action}</header>; }
export function Empty({ title, children, action }: { title: string; children: React.ReactNode; action?: React.ReactNode }) { return <div className="empty"><IconBox icon={BookOpen} /><h3>{title}</h3><p>{children}</p>{action}</div>; }
export function ErrorNotice({ message, retry }: { message: string; retry?: () => void }) { return <div className="notice error" role="alert"><AlertTriangle size={20}/><div><strong>Something needs attention</strong><p>{message}</p>{retry && <button className="text-button" onClick={retry}>Try again <ArrowRight size={15}/></button>}</div></div>; }
export function SafetyNotice({ config, compact = false }: { config: SafetyConfig; compact?: boolean }) {
  const contacts = [['Emergency contact', config.emergency], ['School safeguarding lead', config.safeguarding], ['Counsellor / wellbeing team', config.wellbeing], ['Local crisis resources', config.crisis]].filter(([, value]) => value);
  return <section className="safety-notice" aria-label="Immediate safety concern"><div className="safety-heading"><AlertTriangle size={24}/><div><h2>Immediate safety concern</h2><strong>Do not rely on this tool for emergencies.</strong></div></div><p>Follow your school’s safeguarding/emergency procedures and contact the appropriate qualified professional or emergency service. Do not wait for an analysis or a follow-up reminder.</p>{!compact && <p>Listen calmly, do not promise secrecy, and do not investigate. Record and share factual concerns through the school’s approved safeguarding process.</p>}{contacts.length > 0 ? <dl className="contacts">{contacts.map(([label, value]) => <div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl> : <p className="contact-empty">No local contacts are configured. Follow your school’s emergency/safeguarding procedures and use the appropriate local emergency service if there is immediate danger.</p>}</section>;
}
export function AssessmentRows({ entries }: { entries: Assessment[] }) { return <div className="assessment-list">{entries.map(entry => <button className="assessment-row" key={entry.id} onClick={() => go(`/assessment/${entry.id}`)}><span className="student-avatar">{entry.input.identifier.replace(/Student\s*/i, '').slice(0, 2).toUpperCase()}</span><span className="row-student"><strong>{entry.input.identifier}</strong><span>{entry.input.grade || 'Grade not recorded'} <span aria-hidden="true">·</span> <DateText value={entry.createdAt}/></span></span><span className="row-observations">{entry.input.observations.length} observed change{entry.input.observations.length === 1 ? '' : 's'}</span><Badge level={entry.guidance.concernLevel} safety={entry.guidance.safetyFlag}/><ChevronRight size={18} className="row-arrow"/></button>)}</div>; }
export function FollowUpStatus({ entry }: { entry: Assessment }) { const done = entry.followUp.status === 'complete'; const due = entry.followUp.dueDate <= localDate(); return <span className={`follow-status ${done ? 'done' : due ? 'due' : ''}`}>{done ? <Check size={15}/> : <Clock3 size={15}/>} {done ? 'Follow-up complete' : due ? 'Follow-up due' : 'Scheduled'}{!done && <> · <DateText value={entry.followUp.dueDate}/></>}</span>; }
export function PrivacyStrip() { return <div className="privacy-strip"><ShieldCheck size={18}/><p>A space for thoughtful support. Use anonymous identifiers and fictional information in this prototype.</p><a href="#/about">Safety & privacy <ArrowRight size={14}/></a></div>; }
