import { useEffect, useState } from 'react';
import { ArrowLeft, ArrowRight, BookOpen, CalendarCheck2, Check, ChevronRight, Clock3, Copy, HeartHandshake, Leaf, ListChecks, MessageCircle, Plus, Search, ShieldCheck, Sparkles, Sprout, Trash2, TrendingUp } from 'lucide-react';
import { api } from './api';
import { resources } from '../shared/resources';
import { dateSchema, disclaimer, localDate, type AppConfig, type Assessment } from '../shared/schema';
import { AssessmentRows, Badge, DateText, Empty, ErrorNotice, FollowUpStatus, IconBox, PageHeading, SafetyNotice } from './components';

export function Dashboard({ entries }: { entries: Assessment[] }) {
  const due = entries.filter(e => e.followUp.status === 'pending' && e.followUp.dueDate <= localDate());
  const elevated = entries.filter(e => e.guidance.concernLevel === 'elevated');
  return <>
    <PageHeading eyebrow="A LITTLE AWARENESS GOES A LONG WAY" title="Every student deserves to be seen.">A thoughtful space to turn classroom observations into caring next steps.</PageHeading>
    <section className="hero"><div className="hero-copy"><span className="hero-label"><Sprout size={15}/> TEACHER AWARENESS ASSISTANT</span><h2>Notice changes.<br/>Understand context.<br/><em>Respond with care.</em></h2><p>A change in behavior can be a reason to pause.<br className="desktop-break"/> Let’s find a supportive way forward, together.</p><a href="#/new" className="button cream">Check a concern <ArrowRight size={18}/></a><span className="hero-footnote">A guided reflection · about 3 minutes</span></div><div className="hero-art" aria-hidden="true"><div className="art-orbit"/><div className="art-orbit second"/><svg viewBox="0 0 300 300"><path d="M153 250V108" fill="none" stroke="#e3ebcf" strokeWidth="5" strokeLinecap="round"/><path d="M151 221C90 219 50 171 57 124c62-6 102 37 94 97" fill="#7ea48b"/><path d="M155 190c-2-69 42-100 93-91 4 60-32 96-93 91" fill="#d8e5bc"/><path d="M150 148c-44-2-66-37-58-73 44-1 67 30 58 73" fill="#a6c5a3"/><path d="M154 130c-1-46 26-68 59-66 7 42-18 66-59 66" fill="#f1d9a6"/><path d="M153 249c-30 0-50 7-50 13h101c0-6-23-13-51-13" fill="#113f37"/></svg><div className="art-note"><span><HeartHandshake size={19}/></span>Small check-ins.<br/><strong>Lasting difference.</strong></div></div></section>
    <section className="stats-grid" aria-label="Workspace statistics"><a href="#/history" className="stat-card"><IconBox icon={ListChecks}/><div><span>Total assessments</span><strong>{entries.length.toString().padStart(2, '0')}</strong><p>A record of thoughtful support</p></div><ChevronRight size={17}/></a><a href="#/follow-ups" className="stat-card"><IconBox icon={CalendarCheck2} tone="amber"/><div><span>Follow-ups due</span><strong>{due.length.toString().padStart(2, '0')}<small>{due.length ? 'Ready for a check-in' : 'You’re up to date'}</small></strong><p>Keep the conversation going</p></div><ChevronRight size={17}/></a><a href="#/history" className="stat-card"><IconBox icon={HeartHandshake} tone="lilac"/><div><span>Elevated support signals</span><strong>{elevated.length.toString().padStart(2, '0')}</strong><p>May need school support</p></div><ChevronRight size={17}/></a></section>
    <div className="dashboard-grid"><section className="panel recent-panel"><div className="section-heading"><div><span className="eyebrow">CONTINUE THE CARE</span><h2>Recent assessments</h2></div><a href="#/history" className="text-button">View all <ArrowRight size={15}/></a></div>{entries.length ? <><div className="table-labels"><span>STUDENT & DATE</span><span>SUPPORT SIGNAL</span></div><AssessmentRows entries={entries.slice(0, 4)}/></> : <Empty title="Your first check-in starts here" action={<a href="#/new" className="button primary">Check a concern</a>}>Record an observation and turn it into a supportive next step.</Empty>}<div className="panel-footnote"><ShieldCheck size={15}/> Support signals guide reflection. They are not diagnoses.</div></section><aside className="daily-note"><span className="eyebrow">A MOMENT OF PERSPECTIVE</span><span className="quote-mark">“</span><h2>Start with curiosity,<br/>not a conclusion.</h2><p>A quieter student may need a conversation, not a label. You don’t have to have all the answers to listen.</p><a href="#/resources" className="text-button">Explore conversation tips <ArrowRight size={16}/></a><Leaf className="note-leaf" size={66} strokeWidth={1}/></aside></div>
    <section className="resource-preview"><div className="section-heading"><div><span className="eyebrow">A LITTLE GUIDANCE, WHEN YOU NEED IT</span><h2>For your teaching toolkit</h2></div><a href="#/resources" className="text-button">Explore library <ArrowRight size={15}/></a></div><div className="resource-mini-grid">{[{ icon: Search, title: 'Look beyond the behavior', text: 'Recognise changes without making assumptions.' }, { icon: MessageCircle, title: 'Find the right words', text: 'Gentle ways to start a meaningful conversation.' }, { icon: ShieldCheck, title: 'Know when to get support', text: 'Understand when school support should step in.' }].map(({ icon, title, text }) => <a href="#/resources" className="resource-mini" key={title}><IconBox icon={icon}/><div><h3>{title}</h3><p>{text}</p></div><ArrowRight size={17}/></a>)}</div></section>
  </>;
}

export function History({ entries, followUps }: { entries: Assessment[]; followUps: boolean }) {
  const [search, setSearch] = useState('');
  const [level, setLevel] = useState('all');
  const [status, setStatus] = useState('all');
  const filtered = entries.filter(e => e.input.identifier.toLowerCase().includes(search.toLowerCase()) && (level === 'all' || (level === 'safety' ? e.guidance.safetyFlag : e.guidance.concernLevel === level)) && (status === 'all' || (status === 'due' ? e.followUp.status === 'pending' && e.followUp.dueDate <= localDate() : e.followUp.status === status))).sort((a, b) => followUps ? a.followUp.status.localeCompare(b.followUp.status) * -1 || a.followUp.dueDate.localeCompare(b.followUp.dueDate) : 0);
  return <><PageHeading eyebrow="KEEP THE CONVERSATION GOING" title={followUps ? 'Small check-ins matter.' : 'Your record of care.'} action={<a href="#/new" className="button primary"><Plus size={17}/> New assessment</a>}>{followUps ? 'Review the next step, reconnect, and mark your follow-up when it’s done.' : 'Revisit observations, supportive next steps, and follow-up plans.'}</PageHeading><div className="notice subtle"><ShieldCheck size={20}/><p>{followUps ? 'These reminders are an in-app plan. They do not send notifications, contact staff, or make safeguarding referrals.' : 'This is your browser’s demo workspace. Use fictional identifiers; it is not a secure student record system.'}</p></div><section className="panel history-panel"><div className="filters"><label className="search-field"><Search size={18}/><input aria-label="Search student identifiers" placeholder="Search student identifier…" value={search} onChange={e => setSearch(e.target.value)}/></label><label className="filter-label">Support signal<select value={level} onChange={e => setLevel(e.target.value)}><option value="all">All signals</option><option value="low">Low concern</option><option value="moderate">Moderate concern</option><option value="elevated">Elevated concern</option><option value="safety">Safety concern</option></select></label><label className="filter-label">Follow-up<select value={status} onChange={e => setStatus(e.target.value)}><option value="all">All follow-ups</option><option value="due">Due now</option><option value="pending">Pending</option><option value="complete">Complete</option></select></label></div><div className="history-count">{filtered.length} assessment{filtered.length !== 1 ? 's' : ''}{(search || level !== 'all' || status !== 'all') && <button className="text-button" onClick={() => { setSearch(''); setLevel('all'); setStatus('all'); }}>Clear filters</button>}</div>{filtered.length ? <div className="history-list">{filtered.map(e => <a href={`#/assessment/${e.id}`} className="history-row" key={e.id}><div className="history-row-top"><span className="student-avatar">{e.input.identifier.replace(/Student\s*/i, '').slice(0, 2)}</span><div><h3>{e.input.identifier}</h3><span className="muted">{e.input.grade || 'Grade not recorded'} · <DateText value={e.createdAt}/></span></div><Badge level={e.guidance.concernLevel} safety={e.guidance.safetyFlag}/><ChevronRight size={19}/></div><p>{e.input.observations.slice(0, 3).join(' · ')}{e.input.observations.length > 3 ? ` · +${e.input.observations.length - 3} more` : ''}</p><FollowUpStatus entry={e}/></a>)}</div> : <Empty title={entries.length ? 'No matching assessments' : 'A fresh start'}>{entries.length ? 'Try another identifier or clear the filters.' : 'Create a concern assessment to start your record of support.'}</Empty>}</section></>;
}

export function Results({ id, initial, config, update, onDeleted, notify }: { id: string; initial?: Assessment; config: AppConfig; update: (entry: Assessment) => void; onDeleted: (id: string) => void; notify: (message: string) => void }) {
  const [entry, setEntry] = useState(initial);
  const [error, setError] = useState('');
  const [date, setDate] = useState(initial?.followUp.dueDate || localDate());
  const [busy, setBusy] = useState(false);
  const [deleting, setDeleting] = useState(false);
  const [loading, setLoading] = useState(!initial);
  async function load() { setLoading(true); setError(''); try { const value = await api<Assessment>(`/assessments/${id}`); setEntry(value); setDate(value.followUp.dueDate); } catch (e) { setError((e as Error).message); } finally { setLoading(false); } }
  useEffect(() => { if (!initial) void load(); }, [id]);
  async function patch(value: { dueDate?: string; status?: 'pending' | 'complete' }) { setBusy(true); setError(''); try { const updated = await api<Assessment>(`/assessments/${id}/follow-up`, { method: 'PATCH', body: JSON.stringify(value) }); setEntry(updated); update(updated); notify(value.status === 'complete' ? 'Follow-up marked complete.' : 'Follow-up updated.'); } catch (e) { setError((e as Error).message); } finally { setBusy(false); } }
  async function remove() { setBusy(true); setError(''); try { await api(`/assessments/${id}`, { method: 'DELETE', body: '{}' }); onDeleted(id); } catch (e) { setError((e as Error).message); setBusy(false); } }
  if (loading) return <div className="loading-page" role="status">Loading your assessment…</div>;
  if (!entry) return <ErrorNotice message={error || 'Assessment not found.'} retry={() => void load()}/>;
  const { guidance, input } = entry;
  return <><a href="#/history" className="back-link"><ArrowLeft size={16}/> Assessment history</a><PageHeading eyebrow="FROM OBSERVATION TO SUPPORT" title={`A way forward for ${input.identifier}.`} action={<span className="saved-label"><Check size={16}/> Saved to history</span>}>Recorded <DateText value={entry.createdAt}/> · {input.grade || 'Grade not recorded'} · {input.ageRange}</PageHeading>
    {guidance.safetyFlag && <SafetyNotice config={config.safety}/>}
    <div className={`mode-note ${entry.mode === 'fallback' ? 'fallback' : ''}`}><Sparkles size={17}/><span>{entry.mode === 'ai' ? 'AI-assisted selection of reviewed guidance. Your observations and support signal remain rule-based.' : entry.mode === 'fallback' ? 'AI was unavailable or returned invalid guidance. Reviewed, rule-based guidance was used instead.' : guidance.safetyFlag ? 'Safety pathway · Standard safeguarding guidance. No generic AI advice is used.' : 'Demo guidance · Prepared using transparent rules and reviewed content, without an AI API.'}</span></div>
    <div className="results-layout"><div className="result-main"><section className="panel result-section"><div className="section-heading"><div><span className="eyebrow">01 · OBSERVATIONS</span><h2>What you noticed</h2></div><IconBox icon={Search}/></div><p className="result-summary">{guidance.summary}</p><details className="observation-details"><summary>View recorded context and notes</summary><dl><div><dt>Classroom context</dt><dd>{input.studentContext || 'Not recorded'}</dd></div><div><dt>Related context</dt><dd>{input.contexts.join(', ') || 'Not recorded'}{input.otherContext ? ` — ${input.otherContext}` : ''}</dd></div><div><dt>Teacher notes</dt><dd className="preserve-lines">{input.notes || 'No additional notes'}</dd></div></dl></details></section>
      {!guidance.safetyFlag && <section className="panel result-section"><div className="section-heading"><div><span className="eyebrow">02 · CONSIDER THE CONTEXT</span><h2>Possible areas to consider</h2></div><IconBox icon={TrendingUp}/></div><p className="muted">These are possibilities to explore gently, not conclusions about this student.</p><ul className="factor-list">{guidance.possibleFactors.map(f => <li key={f}><span/><p>{f}</p></li>)}</ul></section>}
      <section className="panel result-section"><div className="section-heading"><div><span className="eyebrow">{guidance.safetyFlag ? '02 · PRIORITISE SAFETY' : '03 · RESPOND WITH CARE'}</span><h2>{guidance.safetyFlag ? 'Follow the safeguarding route' : 'Your next steps'}</h2></div><IconBox icon={HeartHandshake}/></div><ol className="action-list">{guidance.recommendedActions.map((action, i) => <li key={action}><span>{i + 1}</span><p>{action}</p></li>)}</ol></section>
      {!guidance.safetyFlag && <section className="panel result-section conversation-panel"><div className="section-heading"><div><span className="eyebrow">04 · FIND THE WORDS</span><h2>A gentle way to begin</h2></div><MessageCircle size={25}/></div><p>Adapt these to the student and your relationship with them.</p>{guidance.conversationStarters.map(text => <div className="conversation" key={text}><blockquote>{text}</blockquote><button className="icon-button" aria-label={`Copy conversation starter: ${text}`} onClick={async () => { try { await navigator.clipboard.writeText(text); notify('Conversation starter copied.'); } catch { notify('Copy unavailable. Select the conversation text to copy it.'); } }}><Copy size={17}/></button></div>)}</section>}
    </div><aside className="result-aside"><section className="panel signal-card"><span className="eyebrow">SUPPORT SIGNAL</span><Badge level={guidance.concernLevel} safety={guidance.safetyFlag}/><p>{guidance.signalExplanation}</p><div className="signal-footnote"><ShieldCheck size={18}/><span>A support signal, not a medical diagnosis. Your judgment comes first.</span></div></section><section className="panel followup-card"><IconBox icon={CalendarCheck2}/><h2>{guidance.safetyFlag ? 'Record your next action' : 'Keep the care going'}</h2><ul>{guidance.followUpPlan.map(p => <li key={p}>{p}</li>)}</ul><FollowUpStatus entry={entry}/><form onSubmit={e => { e.preventDefault(); if (!dateSchema.safeParse(date).success) { setError('Choose a valid follow-up date.'); return; } void patch({ dueDate: date, status: 'pending' }); }}><label className="field">Follow-up date<input type="date" required value={date} onChange={e => setDate(e.target.value)} max="2100-12-31"/></label><button className="button secondary full" disabled={busy}>Save schedule</button></form><button className="button primary full" disabled={busy} onClick={() => void patch({ status: entry.followUp.status === 'complete' ? 'pending' : 'complete' })}><Check size={16}/>{entry.followUp.status === 'complete' ? 'Reopen follow-up' : 'Mark follow-up complete'}</button><p className="small-print">This records your action only. It does not notify staff or confirm the student is safe.</p></section>{error && <ErrorNotice message={error}/>}<section className="delete-card">{deleting ? <><p>Delete this assessment and its follow-up permanently?</p><div className="delete-actions"><button className="button danger" disabled={busy} onClick={() => void remove()}>Delete permanently</button><button className="text-button" disabled={busy} onClick={() => setDeleting(false)}>Cancel</button></div></> : <button className="text-button danger-text" onClick={() => setDeleting(true)}><Trash2 size={16}/> Delete assessment</button>}</section></aside></div><div className="notice subtle"><ShieldCheck size={20}/><p>{disclaimer}</p></div>
  </>;
}

export function Resources() {
  const [search, setSearch] = useState('');
  const visible = resources.filter(r => `${r.title} ${r.category} ${r.intro}`.toLowerCase().includes(search.toLowerCase()));
  return <><PageHeading eyebrow="YOUR TEACHING TOOLKIT" title="A little guidance. A lot of care.">Practical starting points for noticing changes and supporting students in everyday school life.</PageHeading><div className="library-banner"><IconBox icon={BookOpen}/><div><h2>You don’t have to have all the answers.</h2><p>Start with curiosity, a listening ear, and your school’s support network.</p></div><Sprout size={48} strokeWidth={1}/></div><label className="search-field library-search"><Search size={19}/><input aria-label="Search resources" placeholder="Find a topic, like bullying or conversation…" value={search} onChange={e => setSearch(e.target.value)}/></label><div className="resource-grid">{visible.map((r, index) => <article key={r.id} className="panel resource-card"><div className="resource-card-top"><IconBox icon={[Search, MessageCircle, HeartHandshake, ShieldCheck, Leaf, CalendarCheck2][index % 6]}/><span><Clock3 size={14}/> {r.minutes} min read</span></div><span className="eyebrow">{r.category}</span><h2>{r.title}</h2><p>{r.intro}</p><details><summary>Read practical guidance <ChevronRight size={17}/></summary><ol>{r.steps.map(step => <li key={step}>{step}</li>)}</ol><blockquote>{r.takeaway}</blockquote><a href={r.source} target="_blank" rel="noreferrer">{r.sourceTitle} ↗</a></details></article>)}</div>{!visible.length && <Empty title="No topics found">Try a broader word or clear your search.</Empty>}<p className="small-print resource-disclaimer">Educational guidance only. These resources are not medical advice or a substitute for local safeguarding procedures. Linked sources provide further reading; UK-specific requirements may not apply in your location.</p></>;
}

export function About({ config }: { config: AppConfig }) { return <><PageHeading eyebrow="CLEAR LIMITATIONS. THOUGHTFUL DESIGN." title="Support, with safeguards.">The teacher remains the decision maker. This tool is a starting point for care.</PageHeading><div className="about-grid"><section className="panel result-section"><IconBox icon={ShieldCheck}/><h2>What this tool does</h2><p>{disclaimer}</p><p>It connects observations, context, reviewed guidance, conversation support, and follow-up. It cannot determine whether a student has a mental health condition, and it never replaces a qualified professional.</p><h3>How guidance is prepared</h3><p>The demo uses fixed, transparent rules to choose practical guidance. The optional AI selects from the same reviewed content library; its free-form text is never displayed. Safety answers and a conservative English-language text check can trigger safeguarding guidance.</p><h3>What the support signal means</h3><p>Low means information is limited or recent. Moderate reflects persistence, frequency, multiple observations, or peer/aggression concerns. Elevated reflects a sustained pattern of several frequent changes, or a safety concern. These rules are not clinically validated and are not a measure of medical risk.</p><p>A low signal never proves that a student is safe. Text checks can miss indirect or non-English wording and can overflag quoted or negated wording. Act on your concern regardless of the tool’s result.</p></section><section className="panel result-section"><IconBox icon={ListChecks}/><h2>Your demo data</h2><p>{config.privacy}</p><p>Three fictional examples are created for each new browser workspace. Delete individual assessments from their results page. Anyone with access to the same browser profile can access its workspace.</p><p>{config.aiEnabled ? 'AI is configured. Submitting sends observation fields and notes, excluding the student identifier and grade, to the server’s configured AI provider. Never include real student details.' : 'Demo mode is active. The guidance engine runs on the server without sending observations to an external AI provider.'}</p><h3>Before real school use</h3><p>This prototype needs school approval, appropriate privacy and security controls, verified authentication, retention policies, and professional review. It is not an official student record or safeguarding reporting system.</p><h3>Local support contacts</h3><p>School administrators can configure the emergency contact, safeguarding lead, wellbeing team, and local crisis resources through server environment variables. Contacts are not configured from student input.</p></section></div><SafetyNotice config={config.safety}/></>; }
